all:
	@cd Playtomic && ${MAKE} -f Makefile.openbsd
	@cd demo && ${MAKE} -f Makefile.openbsd

clean:
	@cd Playtomic && ${MAKE} -f Makefile.openbsd clean
	@cd demo && ${MAKE} -f Makefile.openbsd clean

