include ../config/config.linux.Mk
include objects.Mk

BIN=demo

.SUFFIXES: .cpp .o

all: ${BIN}

${BIN}: ${OBJ}
	${CXX} -o ${BIN} ${OBJ} ${LDFLAGS} -L../lib -lplaytomic -lboost_thread-mt -lboost_date_time-mt -lcurl

CXXFLAGS +=-I../CurlWrap -I../json/include -I../Tools
.cpp.o:
	${CXX} -c -I../ -Imodules -o $@ ${CXXFLAGS}  $<

clean:
	rm -f ${OBJ}
	rm -f ${BIN}

