include ../config/config.linux.Mk
include objects.Mk
CXXFLAGS +=-I../CurlWrap -I../json/include
CXXFLAGS +=-I../json/include
LIB=../lib/libplaytomic.so

.SUFFIXES: .cpp .o

all: ${LIB}

${LIB}: ${OBJ}
	${CXX} -shared -o ${LIB} ${OBJ} ${LDFLAGS}


.cpp.o:
	${CXX} -c ${CXXFLAGS} -o $@ -I../Tools $<

clean:
	rm -f ${OBJ}
	rm -f ${LIB}

